version: 2.1

jobs:

  install:
    docker:
      - image: circleci/node:12.19.0
    working_directory: ~/repo
    steps:
      - checkout
      #- restore_cache:
      #    key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: npm install
      #- save_cache:
      #    paths:
      #      - ~/.m2
      #    key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    docker:
      - image: circleci/node:12.19.0
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      #- restore_cache:
      #    key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: npm run build-dev
      #- save_cache:
      #    paths:
      #      - ~/.m2
      #    key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
            
  build-image:
    docker:
      - image: docker:19.03.13
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 19.03.13
          #docker_layer_caching: true
      - run: cp src/index.html build/index.html
      - run: ls build
      - run: $ docker run -it --name frontend -v "$PWD"/build:/usr/src/app -w /usr/src/app node:12.19.0 node bundle.js
      #- run:
      #    name: Build Repos-Manager Docker Image
      #    command: docker build -t repos-manager:$CIRCLE_BRANCH-$CIRCLE_SHA1 .
      #- run:
      #    name: Save Repos-Manager Docker Image to File
      #    command: docker save -o repos-manager-image.tar repos-manager:$CIRCLE_BRANCH-$CIRCLE_SHA1
      #- persist_to_workspace:
      #    root: .
      #    paths:
      #      - ./repos-manager-image.tar

workflows:
  ci-cd:
    jobs:
      - install
      - build:
          requires:
            - install
      - build-image:
          requires:
            - build
