version: 2.1

jobs:

  build:
    docker:
      - image: circleci/node:12.19.0
    working_directory: ~/repo
    steps:
      - checkout
      #- restore_cache:
      #    key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: npm install
      #- save_cache:
      #    paths:
      #      - ~/.m2
      #    key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  ci-cd:
    jobs:
      - build
